New nanny: check Shares' affinity/anti affinity relationships
sapcc/openstack-nannies pull request #78
Opened 2023-07-12 11:11 UTC by chuan137

2023-07-13 16:10 UTC, Carthaca requested changes
Thanks for adding these checks!

I think this would also check soft-deleted shares or am I missing something?
The db queries could get a `deleted='False'` or `deleted=0`  condition respectively

2023-07-13 16:10 UTC, Carthaca commented on scripts/manila-check-affinity.py
> +        violated_rules = []
I would prefer a new variable name instead of recycling

2023-07-13 16:10 UTC, Carthaca commented on scripts/manila-check-affinity.py
> +                    LOG.error("Share %s on host %s", s['share_id'], s['host'])
violated_rules need to be filled in here, otherwise the antiAffinityGauge is always empty

2023-07-27 11:53 UTC, chuan137 commented
> I think this would also check soft-deleted shares or am I missing something? The db queries could get a `deleted='False'` or `deleted=0` condition respectively

thanks, overlooked the conditions. queries updated

2023-08-04 07:01 UTC, Carthaca approved these changes
Thanks

2023-08-04 07:31 UTC, merged